In [53]:
# Import the libraries
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

data = pd.read_csv('../Datasets/Cleaned_data.csv', index_col = [0])
data = data.drop('Assigned.ID', axis = 1)

In [54]:
# Binary encoding for specific columns
binary_encoding = ['SpcHsgGoals', 'Self', 'First', 'Geog']
data[binary_encoding] = data[binary_encoding].replace([2], 0)

data['CoEth'] = data['CoEth'].replace([5], 3)
data['CoRace'] = data['CoRace'].replace([8], 7)
data['CoGender'] = data['CoGender'].replace([4], 3)
data['CoAge'] = data['CoAge'].replace([98], 99)

In [45]:
data.groupby('BoEth').mean()

                MSA     MinPer       LocMedY  Tractrat         Income    IncRat            UPB       LTV   FedGuar        Term    NumBor     First    BoRace    CoRace  BoGender  CoGender      BoAge      CoAge      Geog      Rate     Front      Back  BoCreditScor  CoBoCreditScor       PMI      Self     CoEth  SpcHsgGoals    AcqTyp
BoEth
1      35134.004350  39.708028  70826.257129  1.065796   97671.417110  1.393717  248471.228130  0.797303  0.371677  339.020783  1.507008  0.288062  4.976800  6.015466  1.291928  2.927018  44.104398  71.888835  1.988400  0.040092  0.236156  0.349532      4.029000        6.654422  0.049594  0.079265  2.236829     0.208797  1.129048
2      36193.437554  16.891884  68873.120560  1.176062  108296.391856  1.572289  223409.920018  0.767506  0.192730  335.888122  1.567323  0.203639  4.802453  5.798344  1.279411  2.784603  46.747060  69.606120  1.956649  0.039563  0.207119  0.316245      4.362085        6.453057  0.044367  0.100403  2.435308     0.152071  1.499929
3      33306.704435  25.653856  74340.547450  1.229753  125639.136585  1.705610  291357.507095  0.756962  0.196896  342.070953  1.570732  0.198226  6.695344  6.823282  2.355432  3.171840  46.420399  69.241463  1.964523  0.039583  0.219588  0.326104      4.411086        6.470953  0.038346  0.099113  2.955876     0.109756  1.450333

In [46]:
data.groupby('CoEth').mean()

                MSA     MinPer       LocMedY  Tractrat         Income    IncRat            UPB       LTV   FedGuar        Term    NumBor     First    BoRace    CoRace  BoGender  CoGender      BoAge      CoAge      Geog      Rate     Front      Back  BoCreditScor  CoBoCreditScor       PMI      Self     BoEth  SpcHsgGoals    AcqTyp
CoEth
1      34961.529633  39.268749  72004.690499  1.118961  119828.810913  1.695589  286974.527752  0.786416  0.331138  339.650988  2.025400  0.236124  4.919097  5.076199  1.231421  1.770461  44.886171  44.116651  1.997178  0.040186  0.219794  0.340602      4.170273        4.220132  0.047723  0.097836  1.459078     0.107244  1.129821
2      36715.077992  15.552306  68780.573129  1.196526  126494.525622  1.844698  240512.988895  0.757820  0.141214  332.374610  2.009363  0.150069  4.849314  4.840713  1.177869  1.830950  47.468680  46.601437  1.982144  0.039376  0.192259  0.310174      4.455578        4.459715  0.042054  0.121144  1.991653     0.073819  1.482108
3      35160.489168  20.539537  69893.115734  1.158192   91584.389764  1.301759  216814.673839  0.777038  0.253425  340.534213  1.100574  0.261791  5.075805  6.975633  1.561721  3.858510  45.839367  93.865232  1.933109  0.039770  0.225834  0.325551      4.258320        8.564461  0.045969  0.077814  2.118584     0.229898  1.496036

In [47]:
data.groupby('BoRace').mean()

                 MSA     MinPer       LocMedY  Tractrat         Income    IncRat            UPB       LTV   FedGuar        Term    NumBor     First    CoRace  BoGender  CoGender      BoAge      CoAge      Geog      Rate     Front      Back  BoCreditScor  CoBoCreditScor       PMI      Self     BoEth     CoEth  SpcHsgGoals    AcqTyp
BoRace
1       40786.422961  25.587432  66199.903323  1.064335   87657.800604  1.329839  170625.018127  0.842568  0.643505  337.667674  1.549849  0.347432  5.314199  1.444109  2.755287  44.187311  67.933535  1.993958  0.040224  0.184222  0.307028      3.767372        6.247734  0.031813  0.054381  1.936556  2.453172     0.114804  1.063444
2       33379.986087  42.506191  80579.994783  1.285829  132141.326522  1.652779  387063.316522  0.740648  0.071739  346.638696  1.498261  0.351304  4.913913  1.288261  2.937826  42.538696  72.232174  1.976087  0.040168  0.267291  0.348666      4.426087        6.840870  0.038170  0.106522  2.006522  2.528696     0.136957  1.306522
3       31652.678457  42.701921  76178.023312  1.094262  106740.103698  1.398830  259832.993569  0.844132  0.591640  344.520096  1.364952  0.323955  5.763666  1.404341  3.204180  47.176045  80.047428  1.967042  0.039651  0.230575  0.354986      3.833601        7.220257  0.055973  0.049839  1.999196  2.629421     0.146302  1.270096
4       57080.519553  53.565251  67621.938547  1.129704  116374.592179  1.732220  305952.709497  0.839888  0.826816  341.564246  1.603352  0.351955  5.379888  1.251397  2.698324  45.994413  66.726257  1.972067  0.038614  0.230178  0.367502      4.106145        6.111732  0.033128  0.050279  1.960894  2.396648     0.106145  1.167598
5       36300.079122  15.736199  68236.795741  1.168865  106831.755318  1.565496  215704.002333  0.767063  0.189208  335.155722  1.573405  0.195220  5.851089  1.277453  2.773354  46.860527  69.318423  1.956382  0.039554  0.204896  0.314785      4.365152        6.425839  0.044696  0.101047  1.971244  2.421824     0.155974  1.505003
7       33117.427131  26.341462  74387.801100  1.233569  126258.455087  1.718313  293498.120761  0.759225  0.210128  343.252521  1.569890  0.200733  6.915445  2.367094  3.180339  46.240376  69.332264  1.966086  0.039579  0.220393  0.328600      4.393905        6.470211  0.038414  0.098763  2.876031  2.921861     0.107012  1.431714

In [48]:
data.groupby('CoRace').mean()

                 MSA     MinPer       LocMedY  Tractrat         Income    IncRat            UPB       LTV   FedGuar        Term    NumBor     First    BoRace  BoGender  CoGender      BoAge      CoAge      Geog      Rate     Front      Back  BoCreditScor  CoBoCreditScor       PMI      Self     BoEth     CoEth  SpcHsgGoals    AcqTyp
CoRace
1       36954.485437  27.132136  65639.699029  1.115548  109096.844660  1.684456  205446.252427  0.816408  0.446602  326.796117  2.000000  0.271845  2.864078  1.310680  1.689320  45.932039  44.970874  1.990291  0.040115  0.177369  0.300033      3.912621        4.019417  0.026796  0.048544  1.961165  1.902913     0.058252  1.087379
2       34222.481293  41.567976  80623.969388  1.282320  149165.457483  1.865309  397481.045918  0.733444  0.114796  345.540816  2.040816  0.310374  2.724490  1.189626  1.805272  44.272109  42.993197  1.976190  0.040203  0.245189  0.344632      4.468537        4.463435  0.032372  0.133503  2.002551  2.011905     0.110544  1.278061
3       31784.295285  40.786030  78954.282878  1.130562  135305.841191  1.724191  305078.657568  0.839305  0.605459  341.833747  2.012407  0.280397  3.491315  1.349876  1.657568  47.501241  46.714640  1.992556  0.039496  0.205389  0.349142      3.995037        3.920596  0.050471  0.074442  1.987593  1.985112     0.062035  1.267990
4       58559.009901  58.580693  65784.623762  1.165580  139976.673267  2.165177  343557.940594  0.842574  0.950495  336.237624  2.009901  0.316832  4.287129  1.217822  1.782178  45.702970  44.871287  2.000000  0.038475  0.216126  0.367456      4.207921        4.247525  0.023465  0.049505  1.930693  1.960396     0.029703  1.089109
5       36753.202878  14.673620  68263.458696  1.190922  125197.201316  1.839447  234149.004907  0.758011  0.137520  331.928396  2.008588  0.142687  4.964570  1.176444  1.833965  47.528478  46.671165  1.982564  0.039371  0.190736  0.308943      4.455164        4.460852  0.042693  0.121087  1.977879  1.974868     0.073834  1.486058
7       35149.449009  20.644354  69893.337105  1.158301   91430.367791  1.300164  216874.738255  0.777320  0.254861  340.576257  1.098466  0.262771  5.086638  1.562415  3.862316  45.825625  93.976857  1.933172  0.039771  0.225979  0.325751      4.256362        8.573877  0.045988  0.077557  2.111648  2.988392     0.230364  1.493354

In [59]:
print(data.BoGender.value_counts())
print(data.CoGender.value_counts())
df = data[data.BoGender != 3]
print(df.shape)

1    38402
2    14653
3     2935
Name: BoGender, dtype: int64
3    26438
2    24416
1     5136
Name: CoGender, dtype: int64
(53055, 32)

In [60]:
print(data.BoAge.value_counts())
print(data.CoAge.value_counts())
df = df[df.BoAge != 99]
print(df.shape)

99    2916
36    1735
35    1711
34    1699
32    1687
33    1663
37    1649
31    1566
38    1538
39    1478
30    1456
40    1433
29    1419
42    1280
46    1270
28    1267
41    1267
47    1186
43    1184
27    1182
45    1147
44    1143
48    1116
26    1094
49    1061
53    1045
52    1040
50    1018
51    1002
54     997
55     993
56     919
25     918
57     834
58     799
59     778
24     722
61     721
60     708
62     638
63     603
64     554
65     532
66     500
23     481
67     471
68     419
69     396
70     363
22     320
71     273
72     217
74     204
73     201
75     178
21     168
76     144
77     116
78      91
20      77
79      71
80      61
81      50
84      42
82      41
83      28
19      26
85      24
86      22
87      11
88       8
89       6
92       5
93       3
18       3
91       1
96       1
Name: BoAge, dtype: int64
99    26538
32     1075
34     1049
33     1044
35     1009
36      987
37      963
31      962
30      932
29      919
38      882
39      802
40      758
28      743
41      729
27      700
42      679
46      654
43      651
47      621
44      616
45      609
48      578
26      574
50      552
54      537
52      533
51      519
49      517
53      510
55      502
56      501
25      457
57      454
60      432
58      429
59      426
61      386
24      380
62      359
63      328
64      315
66      308
65      274
67      248
68      245
23      239
69      215
70      192
71      150
22      131
73      103
72      101
74       91
75       86
76       64
21       59
77       54
78       37
20       34
80       31
79       30
82       16
83       13
81       13
84       10
19        8
86        7
85        6
87        5
90        3
92        2
89        2
91        1
93        1
Name: CoAge, dtype: int64
(50270, 32)

In [62]:
print(data.BoRace.value_counts())
print(data.CoRace.value_counts())
df = df[df.BoRace != 7]
print(df.shape)

5    47572
7     4364
2     2300
3     1244
1      331
4      179
Name: BoRace, dtype: int64
7    27309
5    26898
2     1176
3      403
1      103
4      101
Name: CoRace, dtype: int64
(48716, 32)

In [64]:
print(data.BoEth.value_counts())
print(data.CoEth.value_counts())
df = df[df.BoEth != 3]
print(df.shape)

2    49411
3     4510
1     2069
Name: BoEth, dtype: int64
2    27554
3    27373
1     1063
Name: CoEth, dtype: int64
(48230, 32)

In [65]:
missing_cols = ['CoEth', 'CoRace', 'CoAge', 'CoGender']
df = df.drop(missing_cols, axis = 1)

In [66]:
df.shape

(48230, 28)

In [68]:
print(data.BoCreditScor.value_counts())
print(data.CoBoCreditScor.value_counts())
df = df[df.BoEth != 3]
print(df.shape)

5    29892
4    17773
3     6035
2     2066
1      130
9       94
Name: BoCreditScor, dtype: int64
9    24824
5    18307
4     9234
3     2724
2      844
1       57
Name: CoBoCreditScor, dtype: int64
(48230, 28)